---
on:
  pull_request:
  push:

jobs:
  linters: markdown-lint, terraform-lint, terraform-fmt, terraform-validate

#  tests:
#    ...

  check:
    if: always()

    needs:
      - linters
#      - tests

    runs-on: Ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@main
        with:
          allowed-failures:
          allowed-skips:
          jobs: ${{ toJSON(needs) }}
